trainer_params.classifier_optimizer_params.lr:
  desc: null
  value: 0.0002543681581703216
trainer_params.optimizer_params.lr:
  desc: null
  value: 0.001001498579096423
trainer_params.scheduler_params.gamma:
  desc: null
  value: 0.9055135654505578
