stages.0.model_params.classifier_params.margin:
  desc: null
  value: 0.8496602892164838
stages.0.model_params.classifier_params.scale:
  desc: null
  value: 19.264011249574715
trainer_params.classifier_optimizer_params.lr:
  desc: null
  value: 0.0036007127681217262
trainer_params.optimizer_params.lr:
  desc: null
  value: 0.0002972151355323529
trainer_params.scheduler_params.gamma:
  desc: null
  value: 0.8845266589731438
trainer_params.num_epochs:
  desc: null
  value: 128
