stages.0.model_params.classifier_params.margin:
  desc: null
  value: 0.20834288253861077
stages.0.model_params.classifier_params.scale:
  desc: null
  value: 20.14411356995626
trainer_params.classifier_optimizer_params.lr:
  desc: null
  value: 0.008249666255623667
trainer_params.optimizer_params.lr:
  desc: null
  value: 0.00021878178328755177
trainer_params.scheduler_params.gamma:
  desc: null
  value: 0.9949611383305073
trainer_params.num_epochs:
  desc: null
  value: 128
