stages.0.model_params.classifier_params.margin:
  desc: null
  value: 0.49306498126804643
stages.0.model_params.classifier_params.scale:
  desc: null
  value: 18.98653059274058
trainer_params.classifier_optimizer_params.lr:
  desc: null
  value: 0.006483140741625243
trainer_params.optimizer_params.lr:
  desc: null
  value: 0.0001211042478600507
trainer_params.scheduler_params.gamma:
  desc: null
  value: 0.3976761475892261
