model_params.classifier_params.margin:
  desc: null
  value: 0.1
model_params.classifier_params.scale:
  desc: null
  value: 32.0
trainer_params.classifier_optimizer_params.lr:
  desc: null
  value: 0.01
trainer_params.optimizer_params.lr:
  desc: null
  value: 0.001
trainer_params.scheduler_params.gamma:
  desc: null
  value: 0.5
