model_params.classifier_params.margin:
  desc: null
  value: 0.2079054389735946
model_params.classifier_params.scale:
  desc: null
  value: 10.619820209384743
trainer_params.classifier_optimizer_params.lr:
  desc: null
  value: 0.008
trainer_params.optimizer_params.lr:
  desc: null
  value: 0.00007
trainer_params.scheduler_params.gamma:
  desc: null
  value: 0.88
