stages.0.model_params.classifier_params.margin:
  desc: null
  value: 0.2969545792106669
stages.0.model_params.classifier_params.scale:
  desc: null
  value: 25.52320596772025
trainer_params.classifier_optimizer_params.lr:
  desc: null
  value: 0.005932643139096306
trainer_params.optimizer_params.lr:
  desc: null
  value: 6.361853357259656e-05
trainer_params.scheduler_params.gamma:
  desc: null
  value: 0.9897554744188743
