model_params:
  distribution_type: vmf
  distribution_params:
    dim: 128
  classifier_type: loglike
  classifier_params:
    _hopt:
      margin:
        min: 0.0
        max: 64.0
  scorer_type: mls
