model_params:
  distribution_type: vmf
  distribution_params:
    dim: 128
    k: norm
  classifier_type: vmf-loss
  classifier_params:
    _hopt:
      initial_log_scale:
        min: 0.0
        max: 4.0
      kappa_confidence:
        min: 0.1
        max: 1.0
  scorer_type: cosine
criterion_params:
  use_softmax: false
