model_params:
  distribution_type: dirac
  distribution_params:
    dim: 128
    spherical: true
  classifier_type: cosface
  classifier_params:
    _hopt:
      scale:
        min: 1.0
        max: 64.0
      margin:
        min: 0.0
        max: 1.0
  scorer_type: cosine
