fp16: false
grad_scale_growth_interval: 500
num_evaluation_seeds: 10
dataset_params:
  name: serialized-openset
  num_workers: 6
  batch_size: 128
  validation_fold: 0
  uniform_sampling: true
  add_lossy_testsets: true
  add_verification_testsets: true
  train_repeat: 1
  transform_params:
    image_size: 224
    mean: [0.502, 0.459, 0.408]
    std: [0.00392, 0.00392, 0.00392]
  transform_test_params:
    prescale_size: 256
  augmenter_params:
    brightness_range: 0.25
    contrast_range: 0.25
    saturation_range: 0.25
    random_crop_scale: [0.16, 1]
    random_crop_ratio: [0.75, 1.33]
model_params:
  distribution_type: vmf
  classifier_type: vmf-loss
  scorer_type: cosine
  embedder_params:
    model_type: bninception
    pretrained: true
    freeze_bn: true
    head_batchnorm: false
    head_normalize: false
    pooling_type: multi
  distribution_params:
    dim: 128
    k: norm
  classifier_params:
    deterministic_target: true
    initial_log_scale: 1.7322385630806745
    kappa_confidence: 0.4925834887197379
    _hopt:
      initial_log_scale:
        min: 0.0
        max: 4.0
      kappa_confidence:
        min: 0.1
        max: 1.0
trainer_params:
  num_epochs: 128
  selection_dataset: valid
  selection_metric: mapr
  selection_minimize: false
  early_stop_patience: 10
  gradient_clipping: 10
  optimizer_type: sgd
  scheduler_type: step
  optimizer_params:
    lr: 0.00046925338899880587
    weight_decay: 0.0001
    _hopt:
      lr:
        distribution: log_uniform
        min: -11.5
        max: -6.9
  classifier_optimizer_params:
    lr: 0.007315019603503658
    _hopt:
      lr:
        distribution: log_uniform
        min: -9.2
        max: -4.6
  scheduler_params:
    step: 5
    gamma: 0.9596101447181902
    _hopt:
      gamma:
        min: 0.1
        max: 1.0
metrics_params:
  test_classification_metrics:
  - type: nearest
    params:
      num_filter_out_bins: 10
      metrics: [recall, erc-recall@1, erc-mapr, mapr]
      recall_k_values: [1, 2, 4, 8]
  - type: quality
criterion_params:
  use_softmax: false
